#!/bin/bash
#
# tervitab isikut vastavalt kellaajale
#
echo "Mis kell on? "
read aeg
# tingimuslaused
#HOMMIK
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust!"
#PÄEV
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Head päeva!"
#ÕHTU
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Õhtust!"
#ÖÖ
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ööd!"
else
	echo "Sisesta positiivne naturaalarv"
fi
#hihi
#LÕPP
