#!/bin/bash
#
# tervitab isikut nimega, vastavalt kellaajale
#
echo "Mis teie nimi on?"
read nimi
echo "Mis kell on? "
read aeg
# tingimuslaused
#HOMMIK
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
        echo "Tere hommikust, $nimi!"
#PÄEV
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
        echo "Head päeva, $nimi!"
#ÕHTU
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
        echo "Õhtust, $nimi! "
#ÖÖ
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
        echo "Head ööd, $nimi!"
else
        echo "Sisesta positiivne naturaalarv"
fi
#hihi
#LÕPP

